name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
        
jobs:
 install:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Cypress install
          uses: cypress-io/github-action@v6
          with:
            runTests: false
            # config-file: cypress.config.js
           
        - run: npx cypress info
        - run: node --version
        - run: npm start:ci

        - name: "e2e Tests - Chrome"
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          start: npm start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
         
          config-file: cypress.config.ts
        #   working-directory: e2e

        
        # normally you would write
        # uses: cypress-io/github-action@v6
    
      
        # the parameters below are only necessary
        # because we are running these examples in a monorepo

        # with:
        #   working-directory: e2e
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          


