name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
        
jobs:
 install:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout
          uses: actions/checkout@v4
         
    #   uses: cypress-io/github-action@v6
        - name: Cypress install
          uses: cypress-io/github-action@v6
          with:
            build: npx cypress info
            start: npm start:ci
           
            browser: chrome
            # runTests: false 
        
        # normally you would write
        # uses: cypress-io/github-action@v6
    
      
        # the parameters below are only necessary
        # because we are running these examples in a monorepo

        # with:
        #   working-directory: e2e
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          


