name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
  

jobs:

  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v6
        uses: ./
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          working-directory: e2e
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress run